# Generated by Django 4.0.4 on 2022-08-01 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('qualification_certificate', models.ImageField(blank=True, null=True, upload_to='')),
                ('work_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('college_passed_outdate', models.DateField(blank=True, null=True)),
                ('office_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='detail',
        ),
    ]
