# Generated by Django 4.0.4 on 2022-08-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_alter_appointment_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
